import os
from stable_baselines3 import PPO
from stable_baselines3.common.env_checker import check_env
from market_env import SynthMarketEnv

def train():
    print("Initializing the Closed-Loop Synthetic Market Environment...")
    env = SynthMarketEnv()
    
    # Validate that our custom environment follows the OpenAI/Gymnasium standard
    print("Running Gymnasium environment compliance check...")
    check_env(env, warn=True)
    
    print("\nInitializing PPO Trading Agent (Stable-Baselines3)...")
    # PPO (Proximal Policy Optimization) is an industry standard RL algorithm.
    # It strikes a great balance between sample complexity and stability.
    model = PPO("MlpPolicy", env, verbose=1, learning_rate=0.0003, device="cuda" if os.environ.get('CUDA_VISIBLE_DEVICES') else "auto")
    
    total_timesteps = 50000
    print(f"\nTraining RL Agent for {total_timesteps} steps.")
    print("The agent is exploring the infinite synthetic market combinations generated by the GAN.")
    print("Learning to survive 'Black-swan' crashes and exploit bull runs...\n")
    
    # The actual reinforcement learning training phase
    model.learn(total_timesteps=total_timesteps)
    
    # Save our newly trained algorithmic trader
    model.save("ppo_trading_agent")
    print("\nSUCCESS: Training Complete! Saved agent weights to 'ppo_trading_agent.zip'")

if __name__ == "__main__":
    train()
